### ISSUE TITLE
Create Database

### ISSUE THREAD

**Issue by Robo-Dale** [nick3846/RideServiceGroup1#1]
Create the database and query scripts

Database is moddled accordingly
![image](https://user-images.githubusercontent.com/18417985/55865265-48fc1e00-5b7e-11e9-9512-26b6840b3ae5.png)

**Comment by NickolaiWinther** [comment]
Database created
![image](https://user-images.githubusercontent.com/48907409/55869196-54534780-5b86-11e9-96b2-af703ef46093.png)

**Comment by valsby** [comment]
@nick3846  det er smart at du har lagt et billede ind af databasen!
