### ISSUE TITLE
Select a ride

### ISSUE THREAD

**Issue by NickolaiWinther** [nick3846/RideServiceGroup1#12]
When you select a ride, you can see:
- Name
- Category
- Status
- Description
- Number of shutdowns
- Days since last shutdown

**Comment by Robo-Dale** [comment]
I have added a way to shorten text though an extension inside the .Entities project.
The extension class also has a way to translate statuses

**Comment by Robo-Dale** [comment]
Generate a page for each ride clicked
![image](https://user-images.githubusercontent.com/18417985/56721907-310fc700-6746-11e9-8205-0a723ea4bee5.png)

![image](https://user-images.githubusercontent.com/18417985/56722244-f8242200-6746-11e9-89bb-c185285ace62.png)
