### ISSUE TITLE
Create _Layout file

### ISSUE THREAD

**Issue by Robo-Dale** [nick3846/RideServiceGroup1#6]
Adding the layout file from a previous projects, to minimize worktime
_(Creating a layout from scratch is fine too...)_

**Comment by NickolaiWinther** [comment]
suggestion: _Layout file and index file
![image](https://user-images.githubusercontent.com/48907409/55956396-2b08e900-5c64-11e9-806b-117d78856e79.png)
![image](https://user-images.githubusercontent.com/48907409/55956437-3e1bb900-5c64-11e9-8d65-658879a93370.png)
