### ISSUE TITLE
Create Reporistory classes for the items that need a repository 

### ISSUE THREAD

**Issue by Robo-Dale** [nick3846/RideServiceGroup1#7]
Create a repository class for each of the following elements:
- Ride
- Report
- RideCatagory

These classes should take information from the SQL database and process it to usefull information
**Example** 
RideRepository.cs can create a table and read a table from the database
When it reads a table, it should create an entity

**Comment by valsby** [comment]
@Robo-Dale Remember to only make what you need! Don't use a lot of time to make a lot of methods you don't need right now! A GetAll() is of course good, but think about the requirements for Version 1

**Comment by Robo-Dale** [comment]
@davaAspit Appreciate the input! 
I was more concerned about the implementation of methods, when we get to _Version 2_. I am also a tiny bit afraid of using a **GetAll()** method, as it seems like a messy way to do it.

**Comment by valsby** [comment]
I don't get your concern. Number of methods should be scalable under all circumstances.
A GetAll() is pretty normal. A normal setup for a repository includes: GetAll, GetById, Insert, Delete, Update.

**Comment by Robo-Dale** [comment]
Everything should be in order, for now
